version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    command: --quiet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  farmacare-go-development:
    container_name: ${BACKEND_CONTAINER}
    hostname: ${BACKEND_HOST}
    image: "${BACKEND_IMAGE}:${BACKEND_IMAGE_TAG}"
    restart: always
    environment:
      BACKEND_STAGE: ${BACKEND_STAGE}
    ports:
      - "3000:3000"
    volumes:
      - /app/bin
      - ../:/app

networks:
  default:
    name: mongodb_network
